### PR TITLE
Run all archived messages when embedded widget is uninitialized

### LINKED ISSUE #1063: Support `nbconvert --execute`
Hi! I'm Josh, I'm in charge of documentation at [Open Force Field](https://docs.openforcefield.org). We **love** nglview and use it all over the place - in examples, notebooks, talks, visualizing stuff during development, and in our rendered docs. Thank you for your work on it!

I'd like to see if it's possible to get a workflow involving `nbconvert --execute` to work with nglview. I've included some background info documenting where I'm up to, and then have a brief proposal that I think might fix this problem.

# Background

I'm currently setting up a cookbook to store and render all our examples so that users can navigate, access, and read them all in one place. We've used nglview in pre-rendered documentation [before](https://docs.openforcefield.org/projects/toolkit/en/stable/users/molecule_cookbook.html#from-protein-pdb-file), and I was delighted to find that it works out of the box with Sphinx as long as the widget state is saved. Last week while trying to set up automatically executing notebooks, I discovered that this does not work when the notebook is executed with `nbconvert --execute`, as a lot of the initialization occurs in JavaScript which is not run by nbconvert (see #1019, https://github.com/jupyter/nbconvert/issues/2004).

Today I dug in to your code to see if I could figure out what's going on. I couldn't get a dev environment set up - I tried to follow the instructions in CONTRIBUTING.md relating to working in JupyterLab but got a lot of warnings along the lines of "`@lumino/widgets@npm:1.37.2 doesn't provide crypto (p8f630), requested by @lumino/coreutils`", and then an error "`UserWarning: ValueError: Could not find @jupyterlab/builder`". I'll take a crack at seeing what CI does tomorrow but I've never really written anything in JS and everything I've ever tried with NPM has just worked so I don't really know what I'm doing. If someone could double check that the instructions in CONTRIBUTING.md work with a fresh clone (or whatever resets the NPM state) that would be amazing!

What I have figured out is that I can grab `nglview-js-widgets.js` from the CDN, save it to the same directory where I have the rendered notebook in HTML format, and the HTML will use the downloaded file instead of grabbing it from the CDN. With this I've experimented a bit, and it turns out I can get the NBConverted notebook to render just by adding a line to the JavaScript `handleEmbed` function:

(The CDN delivers 3.0.1, not 3.0.5, but I've ported this bit over from the current `master` too)

```javascript
            // Must call _set_representation_from_repr_dict after "fire_embed"
            // User might add Shape (buffer component) to the view and the buffer component
            // is not created yet via loadFile
            // https://github.com/nglviewer/nglview/issues/1003
            var repr_dict = that.model.get("_ngl_repr_dict");
            // Overwrite repr_dict with the default state
            repr_dict = {"0":{"0":{"params":{"aspectRatio":5,"assembly":"default","capped":true,"clipCenter":{"x":0,"y":0,"z":0},"clipNear":0,"clipRadius":0,"colorMode":"hcl","colorReverse":false,"colorScale":"RdYlBu","colorScheme":"chainname","colorValue":9474192,"defaultAssembly":"BU1","depthWrite":true,"diffuse":16777215,"diffuseInterior":false,"disablePicking":false,"flatShaded":false,"interiorColor":2236962,"interiorDarkening":0,"lazy":false,"matrix":{"elements":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},"metalness":0,"opacity":1,"quality":"high","radialSegments":20,"radiusData":{},"radiusScale":0.7,"radiusSize":1,"radiusType":"sstruc","roughness":0.4,"sele":"","side":"double","smoothSheet":false,"subdiv":6,"tension":null,"useInteriorColor":true,"visible":true,"wireframe":false},"type":"cartoon"},"1":{"params":{"aspectRatio":1,"assembly":"default","bondScale":0.4,"clipCenter":{"x":0,"y":0,"z":0},"clipNear":0,"clipRadius":0,"colorMode":"hcl","colorReverse":false,"colorScale":"RdYlBu","colorScheme":"chainname","colorValue":9474192,"cylinderOnly":false,"defaultAssembly":"BU1","depthWrite":true,"diffuse":16777215,"diffuseInterior":false,"disableImpostor":false,"disablePicking":false,"flatShaded":false,"interiorColor":2236962,"interiorDarkening":0,"lazy":false,"lineOnly":false,"linewidth":2,"matrix":{"elements":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},"metalness":0,"opacity":1,"openEnded":true,"quality":"high","radialSegments":20,"radiusData":{},"radiusScale":1,"radiusSize":0.3,"radiusType":"size","roughness":0.4,"sele":"","side":"double","sphereDetail":2,"useInteriorColor":true,"visible":true,"wireframe":false},"type":"base"},"2":{"params":{"aspectRatio":1.5,"assembly":"default","bondScale":0.3,"bondSpacing":0.75,"clipCenter":{"x":0,"y":0,"z":0},"clipNear":0,"clipRadius":0,"colorMode":"hcl","colorReverse":false,"colorScale":"","colorScheme":"element","colorValue":9474192,"cylinderOnly":false,"defaultAssembly":"BU1","depthWrite":true,"diffuse":16777215,"diffuseInterior":false,"disableImpostor":false,"disablePicking":false,"flatShaded":false,"interiorColor":2236962,"interiorDarkening":0,"lazy":false,"lineOnly":false,"linewidth":2,"matrix":{"elements":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},"metalness":0,"multipleBond":"off","opacity":1,"openEnded":true,"quality":"high","radialSegments":20,"radiusData":{},"radiusScale":2,"radiusSize":0.15,"radiusType":"size","roughness":0.4,"sele":"ligand","side":"double","sphereDetail":2,"useInteriorColor":true,"visible":true,"wireframe":false},"type":"ball+stick"}}}
            console.log("repr dict" + JSON.stringify(repr_dict));
            that._set_representation_from_repr_dict(repr_dict);
```

The camera orientation is a bit weird because it is also set by the (non-existent) state information from the notebook. Maybe it's obvious to everyone else that this works but to me it felt like a breakthrough - it demonstrates that it should be possible to get at least default representations working pretty easily on embedded widgets. So what I've surmised about how this all works is:

1. The widget is executed in Python, which involves sending a message containing the structure/trajectory from Python to JS. This message is stored in shared state between Python and JS
2. Different things happen in the notebook to `nbconvert --execute`:
   - In the notebook, JS receives the message, initializes the NGL stage, adds the object, sets up the default representations, configures a camera orientation, and stores all of that (plus anything else the user does to it) in the shared state
   - In nbconvert, no JS is executed, so nothing happens. The shared state includes only the message and the Python default values (mostly empty dicts).
3. The widget state is saved, which involves writing the shared state to the notebook file
4. `nbconvert --to html` stores the state in the HTML page
5. The converted HTML page is opened and JS runs on it. The topology/structure is successfully loaded, but when the `handleEmbed` function is called, different things happen again:
   - In the file that was executed in the notebook: representations, camera orientation, etc are present in the shared state, and are correctly loaded. The widget is reproduced.
   - In the file that was executed with nbconvert: Representations, camera orientation, etc are set to their Python defaults, NOT what JS sets them to after reading the Python defaults. The widget is displayed but has no representations.

# Proposal

If this is right, I think a simple solution might be something like:

1. Add a variable called `_ngl_is_initialized` or `_ngl_js_has_run` or something similar to the shared state, which Python sets to `False` when the widget is created.
2. if `_ngl_is_initialized` is `false`, `handleEmbed` just fires off every message in `_ngl_msg_archive` (not just the `fire_embed` ones), sets `_ngl_is_initialized` to `true`, and returns, skipping setting the model to the stored state. If `_ngl_is_initialized` is `true`, `handleEmbed` maintains its current behavior

This way, the first time the JS is run all the initialization happens, whether that's in the notebook or in the embedded context.

Does this sound right? If I can figure this out, would you accept a PR that implements this? I think it would be really great to have nglview work with a headless executor!

(Also, I'm not precious about writing this - if someones who actually understands JavaScript and NPM and everything else wants to implement this and save me the trouble of figuring all that out I'd be thrilled)

Thanks again for all your work!

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
This PR implements the proposal discussed in #1063.

I made two changes that weren't discussed there:

1. `_ngl_is_initialized` is set in `createStage`, not `handleEmbed`, to ensure it is always set when the JS runs (but also after `handleEmbed`)
2. I had to make `on_msg` async. This is because it is essential that each message completes before the next one is triggered to avoid things like trying to add representations to a missing component. I learnt this the hard way. My understanding is that this won't change behavior - on paths where `on_msg` doesn't `await`, execution will never be suspended and thus the function will run synchronously; on the other hand, when the function does `await` it's the last thing it does, so the only difference is that the `on_msg` function sticks around on the queue instead of the already async inner function. What it does do is allow `on_msg` to be awaited so that messages can be executed and completed in order. This may be of use elsewhere, I'm not sure - I feel like NGLView does sometimes "forget" something I told it.

I also added the `jupyterlab~=3.0` pin to the Conda environment as discussed.

I have a lot of files that have been generated by NPM (or something), including three that are already checked in - so I've added them in a separate commit in case this is a mistake of some sort.

```
	modified:   nglview/static/index.js
	modified:   nglview/static/index.js.map
	modified:   nglview/staticlab/package.json
```

Hope this is useful! I think from what I've learned I can hack something together for my cookbook even if this doesn't get merged, so thanks for your help!

Closes #1063

### CODE REVIEW

**Comment by hai-schrodinger** [comment]
Does this PR actually work as expected?

**Comment by Yoshanuikabundi** [comment]
Yep, seems to! I was surprised too 😂 I made a notebook that creates a widget, clears it's representations and adds new ones. It appears correctly when executed either with `jupyter nbconvert --execute --to html notebook.ipynb` or in JupyterLab. I did have to manually copy over the compiled JavaScript file but my understanding is thats just how the whole embedded widget packaging thing works. I'll put together a more comprehensive demo today.

File: js/src/widget_ngl.ts [hunk 1]
```diff
@@ -398,6 +399,16 @@ class NGLView extends widgets.DOMWidgetView{
     async handleEmbed(){
         var that = this;
         var ngl_msg_archive = that.model.get("_ngl_msg_archive");
+
+        if (!that.model.get("_ngl_is_initialized")) {
+            console.log("No state stored; initializing embedded widget for the first time.");
+            for (const msg of that.model.get("_ngl_msg_archive")) {
+                console.log("Running msg " + JSON.stringify(msg));
+                await that.on_msg(msg);
```
Comment (hainm) [inline js/src/widget_ngl.ts:407]: should update `await` for other places using `on_msg(msg)` too?

**Comment by hainm** [comment]
> I have a lot of files that have been generated by NPM (or something), including three that are already checked in - so I've added them in a separate commit in case this is a mistake of some sort.
> 
> ```
> 	modified:   nglview/static/index.js
> 	modified:   nglview/static/index.js.map
> 	modified:   nglview/staticlab/package.json
> ```

yeah, those files are intentional to be included in `nglview` folder so we don't need `npm` to install the dev nglview python package.

File: js/src/widget_ngl.ts [hunk 2]
```diff
@@ -398,6 +399,16 @@ class NGLView extends widgets.DOMWidgetView{
     async handleEmbed(){
         var that = this;
         var ngl_msg_archive = that.model.get("_ngl_msg_archive");
+
+        if (!that.model.get("_ngl_is_initialized")) {
```
[the remark this answers is not in the document]
Comment (hainm) [reply js/src/widget_ngl.ts:403]: image

[the remark this answers is not in the document]
Comment (hainm) [reply js/src/widget_ngl.ts:403]: or check for both `ngl_full_stage_parameters` and `_camera_orientation`?

[the remark this answers is not in the document]
Comment (Yoshanuikabundi) [reply js/src/widget_ngl.ts]: Done! It looks `_ngl_full_stage_parameters` object is already modified in `createStage`, so I've just made this a shallow copy so that changes aren't reflected in the shared state until we deliberately sync them back up. I think this is more robust to future changes than checking if `_ngl_full_stage_parameters` is the value it is modified to.

**Comment by Yoshanuikabundi** [comment]
OK I've addressed those points! One thing I've noticed is that `js/package.json` still thinks its 3.0.1 - does that need to be updated?

**Comment by hainm** [comment]
> One thing I've noticed is that `js/package.json` still thinks its 3.0.1 - does that need to be updated?

I will do when doing release.

File: js/src/widget_ngl.ts [hunk 3]
```diff
@@ -140,6 +143,7 @@ class NGLView extends widgets.DOMWidgetView{
                 this.set_camera_orientation(that.model.get("_camera_orientation"));
             }
         }
+        that.model.set("_ngl_is_initialized", true)
```
Comment (hainm) [inline js/src/widget_ngl.ts:146]: remove?

Comment (Yoshanuikabundi) [reply js/src/widget_ngl.ts]: Whoops! Fixed.

File: nglview/staticlab/package.json [hunk 4]
```diff
@@ -94,8 +94,14 @@
   "jupyterlab": {
     "extension": "lib/jupyterlab-plugin",
     "outputDir": "nglview-js-widgets/labextension",
+    "sharedPackages": {
+      "@jupyter-widgets/base": {
+        "bundled": false,
+        "singleton": true
+      }
+    },
```
Comment (hainm) [inline nglview/staticlab/package.json:102]: why are those new lines here? I think they already exist to support jupyterlab with iypwidget 8.

Comment (hainm) [reply nglview/staticlab/package.json:102]: oh, this is in `staticlab`.

File: js/src/widget_ngl.ts [hunk 5]
```diff
@@ -104,7 +104,10 @@ class NGLView extends widgets.DOMWidgetView{
 
     createStage(){
         // init NGL stage
-        var stage_params = this.model.get("_ngl_full_stage_parameters");
+        var stage_params = {
+            // Shallow copy so that _ngl_full_stage_parameters is not updated yet
+            ...this.model.get("_ngl_full_stage_parameters")
```
Comment (hainm) [inline js/src/widget_ngl.ts:109]: Does the former code cause trouble?

Comment (Yoshanuikabundi) [reply js/src/widget_ngl.ts:109]: Yeah - see here: https://github.com/nglviewer/nglview/pull/1064#discussion_r1234069046

Basically stage_params was previously a reference to the object inside `_ngl_full_stage_parameters`, so when it was modified `_ngl_full_stage_parameters` was modified immediately. This meant that in `handleEmbed` it wasn't empty anymore, which would make checking it instead of `_ngl_is_initialized` more complicated and fragile. Making it a copy acts more like expected. The object isn't retrieved from the model anywhere except those two methods, and it's stored in the model already after `handleEmbed`, so I don't think this should otherwise change behavior.

**Comment by hainm** [comment]
Thanks @Yoshanuikabundi very much for your contribution.
